# Use postgres/example user/password credentials
version: '3.9'

services:

  pokemon_db:
    image: postgres:alpine3.20
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./data/postgres:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin 
      POSTGRES_DB: pokemonorepo
