name: Project Release
on: 
  push:
    branches:
      - main
  workflow_dispatch:
permissions: 
  contents: write
jobs:
  build-release:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install related dependencies
        run: npm install --legacy-peer-deps
      - name: Trigger prisma generate
        run: npx prisma generate --schema apps/pokemon-be/prisma/schema.prisma
      - name: Trigger Semantic Release
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release